### ISSUE TITLE
Unable to run npm install

### ISSUE THREAD

**Issue by akshaynaik404** [amite/js-links#2]
I forked and cloned the repo and ran `npm install` it gives me following error:   `npm WARN enoent ENOENT: no such file or directory `. package.json is missing.

**Comment by amite** [comment]
Ya sorry - the docs are live but the project isn't. Will update this issue when its ready to roll

**Comment by amite** [comment]
Solved with https://github.com/amite/js-links/commit/faa9b28559765168c235f86fa7fac72b2604d7c9
